---
- name: Ensure that libuser is present
  ansible.builtin.package:
    name: libuser
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure local users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    local: true
    append: false
    groups: "{{ puppeteers_users_localusers_admingroup }}"
    shell: "{{ item.shell | default(puppeteers_users_localusers_shell) }}"
  loop: "{{ puppeteers_users_localusers_users }}"

- name: Ensure passwordless sudo for user
  ansible.builtin.copy:
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL\n"
    dest: "/etc/sudoers.d/99-{{ item.name }}"
    owner: root
    group: root
    mode: '0660'
  loop: "{{ puppeteers_users_localusers_users }}"
  when: item.nopasswd | default(false)

- name: Ensure SSH authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.authorized_key }}"
  loop: "{{ puppeteers_users_localusers_users }}"
